### ISSUE TITLE
IO Error

### ISSUE THREAD

**Issue by jauhararifin** [udhos/equalfile#1]
I was trying to compare two io.Reader using equalfile.CompareReader. The return value is a pair (bool, error).
**The current condition**: If the reader one and reader two has different length, the function will return `(false, fmt.Errorf("compareReaderBufLimit: internal failure: readers returned different sizes")`.
**My expected condition**: It should return `(false, nil)`.
**Reason**: I think when two readers have different length, it means their content are not the same. So we just need to return false. But it is not an error, so you have just to return `(false, nil)`. When you return the error message `"internal failure: readers returned different sizes"`, it makes me hard to know whether the readers have different content or there is an `IO Error`.

**Comment by udhos** [comment]
You are right.
However the code can't simply return (false, nil), since it is reporting an actual defect.
Problem is, readers have returned distinct chunk sizes and current code is unable to compare them.
Of course this ought to be fixed, but the fix is not as simple as returning (false, nil).

**Comment by jauhararifin** [comment]
How about creating a struct `CompareResult` like this:
```
type CompareResult struct {
    matches bool
    cause error
}
```
and make the function return `(CompareResult, error)`, instead of `(bool, error)`

**Comment by udhos** [comment]
Can you please check if this commit fixes the issue for you?

https://github.com/udhos/equalfile/commit/bc7f1b3e03a5e3aa0811681383612d5c99c8cf8b

**Comment by jauhararifin** [comment]
I think it still the same. Unfortunately, i found another unexpected behaviour

```
func TestReader1(t *testing.T) {
	c := New(make([]byte, 4000), Options{MaxSize: int64(50000), Debug: true})
	r1 := strings.NewReader("wow")
	r2 := strings.NewReader("somethingthatlong")
	equal, err := c.CompareReader(r1, r2)
	if equal {
		t.Fatal("CompareReader should returns false")
	}
	fmt.Println(err) // internal failure: readers returned different sizes
}

func TestReader2(t *testing.T) {
	c := New(make([]byte, 2), Options{MaxSize: int64(50000), Debug: true})
	r1 := strings.NewReader("wow")
	r2 := strings.NewReader("somethingthatlong")
	equal, err := c.CompareReader(r1, r2)
	if equal {
		t.Fatal("CompareReader should returns false")
	}
	fmt.Println(err) // <nil>
}
```
Somehow, the first test returns an error. But the second test returns nil. I think the buffer size just for optimation and shouldn't make any difference in the output?

**Comment by udhos** [comment]
What error are you hitting? I have added your tests in commit https://github.com/udhos/equalfile/commit/0c6785417059dd83917908736cf0d02eb549caa2 and am seeing this:

```
$ go test -v
=== RUN   TestCompareLimitBroken
--- PASS: TestCompareLimitBroken (0.00s)
=== RUN   TestCompareBufBroken
--- PASS: TestCompareBufBroken (0.00s)
=== RUN   TestCompareBufSmall
--- PASS: TestCompareBufSmall (0.00s)
=== RUN   TestCompareBufLarge
--- PASS: TestCompareBufLarge (0.10s)
=== RUN   TestCompareLimitBrokenMultiple
--- PASS: TestCompareLimitBrokenMultiple (0.00s)
=== RUN   TestCompareBufBrokenMultiple
--- PASS: TestCompareBufBrokenMultiple (0.00s)
=== RUN   TestCompareBufSmallMultiple
--- PASS: TestCompareBufSmallMultiple (0.00s)
=== RUN   TestCompareBufLargeMultiple
--- PASS: TestCompareBufLargeMultiple (1.86s)
=== RUN   TestReader1
--- PASS: TestReader1 (0.00s)
=== RUN   TestReader2
--- PASS: TestReader2 (0.00s)
=== RUN   TestBrokenReaders
--- PASS: TestBrokenReaders (0.00s)
PASS
ok      github.com/udhos/equalfile      1.986s
```

**Comment by udhos** [comment]
Please notice I have commited the fix for this issue in the branch 'chunk'.
Issue a 'git checkout chunk' before testing.

**Comment by udhos** [comment]
The branch 'chunk' has been merged into 'master'.

**Comment by jauhararifin** [comment]
Oh sorry, I think I forgot to checkout that branch. It looks good to me now
